// WARNING: This file has automatically been generated on Sun, 02 May 2021 14:00:37 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "proj.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

