// WARNING: This file has automatically been generated on Sat, 11 Dec 2021 12:35:48 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *PJ_AREA) Ref() *C.PJ_AREA {
	if x == nil {
		return nil
	}
	return (*C.PJ_AREA)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *PJ_AREA) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewPJ_AREARef converts the C object reference into a raw struct reference without wrapping.
func NewPJ_AREARef(ref unsafe.Pointer) *PJ_AREA {
	return (*PJ_AREA)(ref)
}

// NewPJ_AREA allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewPJ_AREA() *PJ_AREA {
	return (*PJ_AREA)(allocPJ_AREAMemory(1))
}

// allocPJ_AREAMemory allocates memory for type C.PJ_AREA in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPJ_AREAMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPJ_AREAValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPJ_AREAValue = unsafe.Sizeof([1]C.PJ_AREA{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *PJ_AREA) PassRef() *C.PJ_AREA {
	if x == nil {
		x = (*PJ_AREA)(allocPJ_AREAMemory(1))
	}
	return (*C.PJ_AREA)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *PJ) Ref() *C.PJ {
	if x == nil {
		return nil
	}
	return (*C.PJ)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *PJ) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewPJRef converts the C object reference into a raw struct reference without wrapping.
func NewPJRef(ref unsafe.Pointer) *PJ {
	return (*PJ)(ref)
}

// NewPJ allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewPJ() *PJ {
	return (*PJ)(allocPJMemory(1))
}

// allocPJMemory allocates memory for type C.PJ in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPJMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPJValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPJValue = unsafe.Sizeof([1]C.PJ{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *PJ) PassRef() *C.PJ {
	if x == nil {
		x = (*PJ)(allocPJMemory(1))
	}
	return (*C.PJ)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *PJ_CONTEXT) Ref() *C.PJ_CONTEXT {
	if x == nil {
		return nil
	}
	return (*C.PJ_CONTEXT)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *PJ_CONTEXT) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewPJ_CONTEXTRef converts the C object reference into a raw struct reference without wrapping.
func NewPJ_CONTEXTRef(ref unsafe.Pointer) *PJ_CONTEXT {
	return (*PJ_CONTEXT)(ref)
}

// NewPJ_CONTEXT allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewPJ_CONTEXT() *PJ_CONTEXT {
	return (*PJ_CONTEXT)(allocPJ_CONTEXTMemory(1))
}

// allocPJ_CONTEXTMemory allocates memory for type C.PJ_CONTEXT in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPJ_CONTEXTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPJ_CONTEXTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPJ_CONTEXTValue = unsafe.Sizeof([1]C.PJ_CONTEXT{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *PJ_CONTEXT) PassRef() *C.PJ_CONTEXT {
	if x == nil {
		x = (*PJ_CONTEXT)(allocPJ_CONTEXTMemory(1))
	}
	return (*C.PJ_CONTEXT)(unsafe.Pointer(x))
}

// safeString ensures that the string is NULL-terminated, a NULL-terminated copy is created otherwise.
func safeString(str string) string {
	if len(str) > 0 && str[len(str)-1] != '\x00' {
		str = str + "\x00"
	} else if len(str) == 0 {
		str = "\x00"
	}
	return str
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	str = safeString(str)
	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocPCharMemory allocates memory for type *C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPCharValue = unsafe.Sizeof([1]*C.char{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackArgSString transforms a sliced Go data structure into plain C format.
func unpackArgSString(x []string) (unpacked **C.char, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPCharMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.char)(unsafe.Pointer(h0))
	for i0 := range x {
		v0[i0], _ = unpackPCharString(x[i0])
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.char)(h.Data)
	return
}

// packSString reads sliced Go data structure out from plain C format.
func packSString(v []string, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = packPCharString(ptr1)
	}
}

// packPCharString creates a Go string backed by *C.char and avoids copying.
func packPCharString(p *C.char) (raw string) {
	if p != nil && *p != 0 {
		h := (*stringHeader)(unsafe.Pointer(&raw))
		h.Data = unsafe.Pointer(p)
		for *p != 0 {
			p = (*C.char)(unsafe.Pointer(uintptr(unsafe.Pointer(p)) + 1)) // p++
		}
		h.Len = int(uintptr(unsafe.Pointer(p)) - uintptr(h.Data))
	}
	return
}

// RawString reperesents a string backed by data on the C side.
type RawString string

// Copy returns a Go-managed copy of raw string.
func (raw RawString) Copy() string {
	if len(raw) == 0 {
		return ""
	}
	h := (*stringHeader)(unsafe.Pointer(&raw))
	return C.GoStringN((*C.char)(h.Data), C.int(h.Len))
}
