// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 17 Dec 2019 13:19:11 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "proj.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

