// WARNING: This file has automatically been generated on Wed, 01 Jan 2020 21:23:02 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "proj.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

