// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Dec 2019 15:08:31 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// PJ_LOG_LEVEL as declared in include/proj.h:320
type PJ_LOG_LEVEL int32

// PJ_LOG_LEVEL enumeration from include/proj.h:320
const ()

// PJ_GUESSED_WKT_DIALECT as declared in include/proj.h:495
type PJ_GUESSED_WKT_DIALECT int32

// PJ_GUESSED_WKT_DIALECT enumeration from include/proj.h:495
const ()

// PJ_CATEGORY as declared in include/proj.h:505
type PJ_CATEGORY int32

// PJ_CATEGORY enumeration from include/proj.h:505
const ()

// PJ_TYPE as declared in include/proj.h:546
type PJ_TYPE int32

// PJ_TYPE enumeration from include/proj.h:546
const ()

// PJ_COMPARISON_CRITERION as declared in include/proj.h:568
type PJ_COMPARISON_CRITERION int32

// PJ_COMPARISON_CRITERION enumeration from include/proj.h:568
const ()

// PJ_WKT_TYPE as declared in include/proj.h:586
type PJ_WKT_TYPE int32

// PJ_WKT_TYPE enumeration from include/proj.h:586
const ()

// PROJ_CRS_EXTENT_USE as declared in include/proj.h:605
type PROJ_CRS_EXTENT_USE int32

// PROJ_CRS_EXTENT_USE enumeration from include/proj.h:605
const ()

// PROJ_GRID_AVAILABILITY_USE as declared in include/proj.h:619
type PROJ_GRID_AVAILABILITY_USE int32

// PROJ_GRID_AVAILABILITY_USE enumeration from include/proj.h:619
const ()

// PJ_PROJ_STRING_TYPE as declared in include/proj.h:628
type PJ_PROJ_STRING_TYPE int32

// PJ_PROJ_STRING_TYPE enumeration from include/proj.h:628
const ()

// PROJ_SPATIAL_CRITERION as declared in include/proj.h:639
type PROJ_SPATIAL_CRITERION int32

// PROJ_SPATIAL_CRITERION enumeration from include/proj.h:639
const ()

// PROJ_INTERMEDIATE_CRS_USE as declared in include/proj.h:652
type PROJ_INTERMEDIATE_CRS_USE int32

// PROJ_INTERMEDIATE_CRS_USE enumeration from include/proj.h:652
const ()

// PJ_COORDINATE_SYSTEM_TYPE as declared in include/proj.h:668
type PJ_COORDINATE_SYSTEM_TYPE int32

// PJ_COORDINATE_SYSTEM_TYPE enumeration from include/proj.h:668
const ()

// PJ_DIRECTION as declared in include/proj.h:378
type PJ_DIRECTION int32

// PJ_DIRECTION enumeration from include/proj.h:378
const ()
