// WARNING: This file has automatically been generated on Sat, 11 Dec 2021 12:35:48 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// PJ_DIRECTION as declared in include/proj.h:580
type PJ_DIRECTION int32

// PJ_DIRECTION enumeration from include/proj.h:580
const ()
