// WARNING: This file has automatically been generated on Sun, 02 May 2021 16:07:07 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// PROJ_CRS_EXTENT_USE as declared in include/proj.h:605
type PROJ_CRS_EXTENT_USE int32

// PROJ_CRS_EXTENT_USE enumeration from include/proj.h:605
const ()

// PROJ_GRID_AVAILABILITY_USE as declared in include/proj.h:619
type PROJ_GRID_AVAILABILITY_USE int32

// PROJ_GRID_AVAILABILITY_USE enumeration from include/proj.h:619
const ()

// PROJ_SPATIAL_CRITERION as declared in include/proj.h:639
type PROJ_SPATIAL_CRITERION int32

// PROJ_SPATIAL_CRITERION enumeration from include/proj.h:639
const ()

// PROJ_INTERMEDIATE_CRS_USE as declared in include/proj.h:652
type PROJ_INTERMEDIATE_CRS_USE int32

// PROJ_INTERMEDIATE_CRS_USE enumeration from include/proj.h:652
const ()

// PJ_DIRECTION as declared in include/proj.h:378
type PJ_DIRECTION int32

// PJ_DIRECTION enumeration from include/proj.h:378
const ()
