// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Dec 2019 15:08:31 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// Context_create function as declared in include/proj.h:344
func Context_create() *PJ_CONTEXT {
	__ret := C.proj_context_create()
	__v := *(**PJ_CONTEXT)(unsafe.Pointer(&__ret))
	return __v
}

// Context_destroy function as declared in include/proj.h:345
func Context_destroy(ctx []PJ_CONTEXT) *PJ_CONTEXT {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	__ret := C.proj_context_destroy(cctx)
	__v := *(**PJ_CONTEXT)(unsafe.Pointer(&__ret))
	return __v
}

// Context_use_proj4_init_rules function as declared in include/proj.h:353
func Context_use_proj4_init_rules(ctx []PJ_CONTEXT, enable int32) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cenable, _ := (C.int)(enable), cgoAllocsUnknown
	C.proj_context_use_proj4_init_rules(cctx, cenable)
}

// Context_get_use_proj4_init_rules function as declared in include/proj.h:354
func Context_get_use_proj4_init_rules(ctx []PJ_CONTEXT, from_legacy_code_path int32) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfrom_legacy_code_path, _ := (C.int)(from_legacy_code_path), cgoAllocsUnknown
	__ret := C.proj_context_get_use_proj4_init_rules(cctx, cfrom_legacy_code_path)
	__v := (int32)(__ret)
	return __v
}

// Create function as declared in include/proj.h:357
func Create(ctx *PJ_CONTEXT, definition string) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	definition = safeString(definition)
	cdefinition, _ := unpackPCharString(definition)
	__ret := C.proj_create(cctx, cdefinition)
	runtime.KeepAlive(definition)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Create_argv function as declared in include/proj.h:358
func Create_argv(ctx []PJ_CONTEXT, argc int32, argv [][]byte) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cargc, _ := (C.int)(argc), cgoAllocsUnknown
	cargv, _ := unpackArgSSByte(argv)
	__ret := C.proj_create_argv(cctx, cargc, cargv)
	packSSByte(argv, cargv)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Create_crs_to_crs function as declared in include/proj.h:359
func Create_crs_to_crs(ctx *PJ_CONTEXT, source_crs string, target_crs string, area *PJ_AREA) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	source_crs = safeString(source_crs)
	csource_crs, _ := unpackPCharString(source_crs)
	target_crs = safeString(target_crs)
	ctarget_crs, _ := unpackPCharString(target_crs)
	carea, _ := (*C.PJ_AREA)(unsafe.Pointer(area)), cgoAllocsUnknown
	__ret := C.proj_create_crs_to_crs(cctx, csource_crs, ctarget_crs, carea)
	runtime.KeepAlive(target_crs)
	runtime.KeepAlive(source_crs)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Create_crs_to_crs_from_pj function as declared in include/proj.h:360
func Create_crs_to_crs_from_pj(ctx []PJ_CONTEXT, source_crs []PJ, target_crs []PJ, area []PJ_AREA, options []string) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	csource_crs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&source_crs)).Data)), cgoAllocsUnknown
	ctarget_crs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&target_crs)).Data)), cgoAllocsUnknown
	carea, _ := (*C.PJ_AREA)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&area)).Data)), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_create_crs_to_crs_from_pj(cctx, csource_crs, ctarget_crs, carea, coptions)
	packSString(options, coptions)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Normalize_for_visualization function as declared in include/proj.h:365
func Normalize_for_visualization(ctx []PJ_CONTEXT, obj []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_normalize_for_visualization(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Destroy function as declared in include/proj.h:366
func Destroy(P []PJ) *PJ {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	__ret := C.proj_destroy(cP)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Area_create function as declared in include/proj.h:369
func Area_create() *PJ_AREA {
	__ret := C.proj_area_create()
	__v := *(**PJ_AREA)(unsafe.Pointer(&__ret))
	return __v
}

// Area_set_bbox function as declared in include/proj.h:370
func Area_set_bbox(area []PJ_AREA, west_lon_degree float64, south_lat_degree float64, east_lon_degree float64, north_lat_degree float64) {
	carea, _ := (*C.PJ_AREA)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&area)).Data)), cgoAllocsUnknown
	cwest_lon_degree, _ := (C.double)(west_lon_degree), cgoAllocsUnknown
	csouth_lat_degree, _ := (C.double)(south_lat_degree), cgoAllocsUnknown
	ceast_lon_degree, _ := (C.double)(east_lon_degree), cgoAllocsUnknown
	cnorth_lat_degree, _ := (C.double)(north_lat_degree), cgoAllocsUnknown
	C.proj_area_set_bbox(carea, cwest_lon_degree, csouth_lat_degree, ceast_lon_degree, cnorth_lat_degree)
}

// Area_destroy function as declared in include/proj.h:375
func Area_destroy(area []PJ_AREA) {
	carea, _ := (*C.PJ_AREA)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&area)).Data)), cgoAllocsUnknown
	C.proj_area_destroy(carea)
}

// Angular_input function as declared in include/proj.h:386
func Angular_input(P []PJ, dir PJ_DIRECTION) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cdir, _ := (C.enum_PJ_DIRECTION)(dir), cgoAllocsUnknown
	__ret := C.proj_angular_input(cP, cdir)
	__v := (int32)(__ret)
	return __v
}

// Angular_output function as declared in include/proj.h:387
func Angular_output(P []PJ, dir PJ_DIRECTION) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cdir, _ := (C.enum_PJ_DIRECTION)(dir), cgoAllocsUnknown
	__ret := C.proj_angular_output(cP, cdir)
	__v := (int32)(__ret)
	return __v
}

// Trans function as declared in include/proj.h:390
func Trans(P []PJ, direction PJ_DIRECTION, coord PJ_COORD) PJ_COORD {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cdirection, _ := (C.PJ_DIRECTION)(direction), cgoAllocsUnknown
	ccoord, _ := *(*C.PJ_COORD)(unsafe.Pointer(&coord)), cgoAllocsUnknown
	__ret := C.proj_trans(cP, cdirection, ccoord)
	__v := *(*PJ_COORD)(unsafe.Pointer(&__ret))
	return __v
}

// Trans_array function as declared in include/proj.h:391
func Trans_array(P []PJ, direction PJ_DIRECTION, n uint, coord []PJ_COORD) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cdirection, _ := (C.PJ_DIRECTION)(direction), cgoAllocsUnknown
	cn, _ := (C.size_t)(n), cgoAllocsUnknown
	ccoord, _ := (*C.PJ_COORD)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coord)).Data)), cgoAllocsUnknown
	__ret := C.proj_trans_array(cP, cdirection, cn, ccoord)
	__v := (int32)(__ret)
	return __v
}

// Trans_generic function as declared in include/proj.h:392
func Trans_generic(P []PJ, direction PJ_DIRECTION, x []float64, sx uint, nx uint, y []float64, sy uint, ny uint, z []float64, sz uint, nz uint, t []float64, st uint, nt uint) uint {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cdirection, _ := (C.PJ_DIRECTION)(direction), cgoAllocsUnknown
	cx, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x)).Data)), cgoAllocsUnknown
	csx, _ := (C.size_t)(sx), cgoAllocsUnknown
	cnx, _ := (C.size_t)(nx), cgoAllocsUnknown
	cy, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&y)).Data)), cgoAllocsUnknown
	csy, _ := (C.size_t)(sy), cgoAllocsUnknown
	cny, _ := (C.size_t)(ny), cgoAllocsUnknown
	cz, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&z)).Data)), cgoAllocsUnknown
	csz, _ := (C.size_t)(sz), cgoAllocsUnknown
	cnz, _ := (C.size_t)(nz), cgoAllocsUnknown
	ct, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&t)).Data)), cgoAllocsUnknown
	cst, _ := (C.size_t)(st), cgoAllocsUnknown
	cnt, _ := (C.size_t)(nt), cgoAllocsUnknown
	__ret := C.proj_trans_generic(cP, cdirection, cx, csx, cnx, cy, csy, cny, cz, csz, cnz, ct, cst, cnt)
	__v := (uint)(__ret)
	return __v
}

// Coord function as declared in include/proj.h:403
func Coord(x float64, y float64, z float64, t float64) PJ_COORD {
	cx, _ := (C.double)(x), cgoAllocsUnknown
	cy, _ := (C.double)(y), cgoAllocsUnknown
	cz, _ := (C.double)(z), cgoAllocsUnknown
	ct, _ := (C.double)(t), cgoAllocsUnknown
	__ret := C.proj_coord(cx, cy, cz, ct)
	__v := *(*PJ_COORD)(unsafe.Pointer(&__ret))
	return __v
}

// Roundtrip function as declared in include/proj.h:406
func Roundtrip(P []PJ, direction PJ_DIRECTION, n int32, coord []PJ_COORD) float64 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cdirection, _ := (C.PJ_DIRECTION)(direction), cgoAllocsUnknown
	cn, _ := (C.int)(n), cgoAllocsUnknown
	ccoord, _ := (*C.PJ_COORD)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coord)).Data)), cgoAllocsUnknown
	__ret := C.proj_roundtrip(cP, cdirection, cn, ccoord)
	__v := (float64)(__ret)
	return __v
}

// Lp_dist function as declared in include/proj.h:409
func Lp_dist(P []PJ, a PJ_COORD, b PJ_COORD) float64 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	ca, _ := *(*C.PJ_COORD)(unsafe.Pointer(&a)), cgoAllocsUnknown
	cb, _ := *(*C.PJ_COORD)(unsafe.Pointer(&b)), cgoAllocsUnknown
	__ret := C.proj_lp_dist(cP, ca, cb)
	__v := (float64)(__ret)
	return __v
}

// Lpz_dist function as declared in include/proj.h:412
func Lpz_dist(P []PJ, a PJ_COORD, b PJ_COORD) float64 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	ca, _ := *(*C.PJ_COORD)(unsafe.Pointer(&a)), cgoAllocsUnknown
	cb, _ := *(*C.PJ_COORD)(unsafe.Pointer(&b)), cgoAllocsUnknown
	__ret := C.proj_lpz_dist(cP, ca, cb)
	__v := (float64)(__ret)
	return __v
}

// Xy_dist function as declared in include/proj.h:415
func Xy_dist(a PJ_COORD, b PJ_COORD) float64 {
	ca, _ := *(*C.PJ_COORD)(unsafe.Pointer(&a)), cgoAllocsUnknown
	cb, _ := *(*C.PJ_COORD)(unsafe.Pointer(&b)), cgoAllocsUnknown
	__ret := C.proj_xy_dist(ca, cb)
	__v := (float64)(__ret)
	return __v
}

// Xyz_dist function as declared in include/proj.h:418
func Xyz_dist(a PJ_COORD, b PJ_COORD) float64 {
	ca, _ := *(*C.PJ_COORD)(unsafe.Pointer(&a)), cgoAllocsUnknown
	cb, _ := *(*C.PJ_COORD)(unsafe.Pointer(&b)), cgoAllocsUnknown
	__ret := C.proj_xyz_dist(ca, cb)
	__v := (float64)(__ret)
	return __v
}

// Geod function as declared in include/proj.h:421
func Geod(P []PJ, a PJ_COORD, b PJ_COORD) PJ_COORD {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	ca, _ := *(*C.PJ_COORD)(unsafe.Pointer(&a)), cgoAllocsUnknown
	cb, _ := *(*C.PJ_COORD)(unsafe.Pointer(&b)), cgoAllocsUnknown
	__ret := C.proj_geod(cP, ca, cb)
	__v := *(*PJ_COORD)(unsafe.Pointer(&__ret))
	return __v
}

// Context_errno function as declared in include/proj.h:425
func Context_errno(ctx []PJ_CONTEXT) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	__ret := C.proj_context_errno(cctx)
	__v := (int32)(__ret)
	return __v
}

// Errno function as declared in include/proj.h:426
func Errno(P []PJ) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	__ret := C.proj_errno(cP)
	__v := (int32)(__ret)
	return __v
}

// Errno_set function as declared in include/proj.h:427
func Errno_set(P []PJ, err int32) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cerr, _ := (C.int)(err), cgoAllocsUnknown
	__ret := C.proj_errno_set(cP, cerr)
	__v := (int32)(__ret)
	return __v
}

// Errno_reset function as declared in include/proj.h:428
func Errno_reset(P []PJ) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	__ret := C.proj_errno_reset(cP)
	__v := (int32)(__ret)
	return __v
}

// Errno_restore function as declared in include/proj.h:429
func Errno_restore(P []PJ, err int32) int32 {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	cerr, _ := (C.int)(err), cgoAllocsUnknown
	__ret := C.proj_errno_restore(cP, cerr)
	__v := (int32)(__ret)
	return __v
}

// Errno_string function as declared in include/proj.h:430
func Errno_string(err int32) string {
	cerr, _ := (C.int)(err), cgoAllocsUnknown
	__ret := C.proj_errno_string(cerr)
	__v := packPCharString(__ret)
	return __v
}

// Log_level function as declared in include/proj.h:432
func Log_level(ctx []PJ_CONTEXT, log_level PJ_LOG_LEVEL) PJ_LOG_LEVEL {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	clog_level, _ := (C.PJ_LOG_LEVEL)(log_level), cgoAllocsUnknown
	__ret := C.proj_log_level(cctx, clog_level)
	__v := (PJ_LOG_LEVEL)(__ret)
	return __v
}

// Factors function as declared in include/proj.h:436
func Factors(P []PJ, lp PJ_COORD) PJ_FACTORS {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	clp, _ := *(*C.PJ_COORD)(unsafe.Pointer(&lp)), cgoAllocsUnknown
	__ret := C.proj_factors(cP, clp)
	__v := *NewPJ_FACTORSRef(unsafe.Pointer(&__ret))
	return __v
}

// Info function as declared in include/proj.h:439
func Info() PJ_INFO {
	__ret := C.proj_info()
	__v := *NewPJ_INFORef(unsafe.Pointer(&__ret))
	return __v
}

// Pj_info function as declared in include/proj.h:440
func Pj_info(P []PJ) PJ_PROJ_INFO {
	cP, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&P)).Data)), cgoAllocsUnknown
	__ret := C.proj_pj_info(cP)
	__v := *NewPJ_PROJ_INFORef(unsafe.Pointer(&__ret))
	return __v
}

// Grid_info function as declared in include/proj.h:441
func Grid_info(gridname string) PJ_GRID_INFO {
	gridname = safeString(gridname)
	cgridname, _ := unpackPCharString(gridname)
	__ret := C.proj_grid_info(cgridname)
	runtime.KeepAlive(gridname)
	__v := *NewPJ_GRID_INFORef(unsafe.Pointer(&__ret))
	return __v
}

// Init_info function as declared in include/proj.h:442
func Init_info(initname string) PJ_INIT_INFO {
	initname = safeString(initname)
	cinitname, _ := unpackPCharString(initname)
	__ret := C.proj_init_info(cinitname)
	runtime.KeepAlive(initname)
	__v := *NewPJ_INIT_INFORef(unsafe.Pointer(&__ret))
	return __v
}

// List_operations function as declared in include/proj.h:446
func List_operations() *PJ_OPERATIONS {
	__ret := C.proj_list_operations()
	__v := NewPJ_OPERATIONSRef(unsafe.Pointer(__ret))
	return __v
}

// List_ellps function as declared in include/proj.h:447
func List_ellps() *PJ_ELLPS {
	__ret := C.proj_list_ellps()
	__v := NewPJ_ELLPSRef(unsafe.Pointer(__ret))
	return __v
}

// List_units function as declared in include/proj.h:448
func List_units() *PJ_UNITS {
	__ret := C.proj_list_units()
	__v := NewPJ_UNITSRef(unsafe.Pointer(__ret))
	return __v
}

// List_angular_units function as declared in include/proj.h:449
func List_angular_units() *PJ_UNITS {
	__ret := C.proj_list_angular_units()
	__v := NewPJ_UNITSRef(unsafe.Pointer(__ret))
	return __v
}

// List_prime_meridians function as declared in include/proj.h:450
func List_prime_meridians() *PJ_PRIME_MERIDIANS {
	__ret := C.proj_list_prime_meridians()
	__v := NewPJ_PRIME_MERIDIANSRef(unsafe.Pointer(__ret))
	return __v
}

// Torad function as declared in include/proj.h:455
func Torad(angle_in_degrees float64) float64 {
	cangle_in_degrees, _ := (C.double)(angle_in_degrees), cgoAllocsUnknown
	__ret := C.proj_torad(cangle_in_degrees)
	__v := (float64)(__ret)
	return __v
}

// Todeg function as declared in include/proj.h:456
func Todeg(angle_in_radians float64) float64 {
	cangle_in_radians, _ := (C.double)(angle_in_radians), cgoAllocsUnknown
	__ret := C.proj_todeg(cangle_in_radians)
	__v := (float64)(__ret)
	return __v
}

// Dmstor function as declared in include/proj.h:458
func Dmstor(is string, rs [][]byte) float64 {
	is = safeString(is)
	cis, _ := unpackPCharString(is)
	crs, _ := unpackArgSSByte(rs)
	__ret := C.proj_dmstor(cis, crs)
	packSSByte(rs, crs)
	runtime.KeepAlive(is)
	__v := (float64)(__ret)
	return __v
}

// Rtodms function as declared in include/proj.h:459
func Rtodms(s []byte, r float64, pos int32, neg int32) *byte {
	cs, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&s)).Data)), cgoAllocsUnknown
	cr, _ := (C.double)(r), cgoAllocsUnknown
	cpos, _ := (C.int)(pos), cgoAllocsUnknown
	cneg, _ := (C.int)(neg), cgoAllocsUnknown
	__ret := C.proj_rtodms(cs, cr, cpos, cneg)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// Cleanup function as declared in include/proj.h:461
func Cleanup() {
	C.proj_cleanup()
}

// Context_set_autoclose_database function as declared in include/proj.h:765
func Context_set_autoclose_database(ctx []PJ_CONTEXT, autoclose int32) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cautoclose, _ := (C.int)(autoclose), cgoAllocsUnknown
	C.proj_context_set_autoclose_database(cctx, cautoclose)
}

// Context_set_database_path function as declared in include/proj.h:768
func Context_set_database_path(ctx *PJ_CONTEXT, dbPath string, auxDbPaths []string, options []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	dbPath = safeString(dbPath)
	cdbPath, _ := unpackPCharString(dbPath)
	cauxDbPaths, _ := unpackArgSString(auxDbPaths)
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_context_set_database_path(cctx, cdbPath, cauxDbPaths, coptions)
	packSString(options, coptions)
	packSString(auxDbPaths, cauxDbPaths)
	runtime.KeepAlive(dbPath)
	__v := (int32)(__ret)
	return __v
}

// Context_get_database_path function as declared in include/proj.h:773
func Context_get_database_path(ctx *PJ_CONTEXT) string {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.proj_context_get_database_path(cctx)
	__v := packPCharString(__ret)
	return __v
}

// Context_get_database_metadata function as declared in include/proj.h:775
func Context_get_database_metadata(ctx []PJ_CONTEXT, key string) string {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	key = safeString(key)
	ckey, _ := unpackPCharString(key)
	__ret := C.proj_context_get_database_metadata(cctx, ckey)
	runtime.KeepAlive(key)
	__v := packPCharString(__ret)
	return __v
}

// Context_guess_wkt_dialect function as declared in include/proj.h:779
func Context_guess_wkt_dialect(ctx []PJ_CONTEXT, wkt string) PJ_GUESSED_WKT_DIALECT {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	wkt = safeString(wkt)
	cwkt, _ := unpackPCharString(wkt)
	__ret := C.proj_context_guess_wkt_dialect(cctx, cwkt)
	runtime.KeepAlive(wkt)
	__v := (PJ_GUESSED_WKT_DIALECT)(__ret)
	return __v
}

// Create_from_database function as declared in include/proj.h:787
func Create_from_database(ctx []PJ_CONTEXT, auth_name string, code string, category PJ_CATEGORY, usePROJAlternativeGridNames int32, options []string) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	auth_name = safeString(auth_name)
	cauth_name, _ := unpackPCharString(auth_name)
	code = safeString(code)
	ccode, _ := unpackPCharString(code)
	ccategory, _ := (C.PJ_CATEGORY)(category), cgoAllocsUnknown
	cusePROJAlternativeGridNames, _ := (C.int)(usePROJAlternativeGridNames), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_create_from_database(cctx, cauth_name, ccode, ccategory, cusePROJAlternativeGridNames, coptions)
	packSString(options, coptions)
	runtime.KeepAlive(code)
	runtime.KeepAlive(auth_name)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Uom_get_info_from_database function as declared in include/proj.h:794
func Uom_get_info_from_database(ctx []PJ_CONTEXT, auth_name string, code string, out_name []string, out_conv_factor []float64, out_category []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	auth_name = safeString(auth_name)
	cauth_name, _ := unpackPCharString(auth_name)
	code = safeString(code)
	ccode, _ := unpackPCharString(code)
	cout_name, _ := unpackArgSString(out_name)
	cout_conv_factor, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_conv_factor)).Data)), cgoAllocsUnknown
	cout_category, _ := unpackArgSString(out_category)
	__ret := C.proj_uom_get_info_from_database(cctx, cauth_name, ccode, cout_name, cout_conv_factor, cout_category)
	packSString(out_category, cout_category)
	packSString(out_name, cout_name)
	runtime.KeepAlive(code)
	runtime.KeepAlive(auth_name)
	__v := (int32)(__ret)
	return __v
}

// Grid_get_info_from_database function as declared in include/proj.h:801
func Grid_get_info_from_database(ctx []PJ_CONTEXT, grid_name string, out_full_name []string, out_package_name []string, out_url []string, out_direct_download []int32, out_open_license []int32, out_available []int32) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	grid_name = safeString(grid_name)
	cgrid_name, _ := unpackPCharString(grid_name)
	cout_full_name, _ := unpackArgSString(out_full_name)
	cout_package_name, _ := unpackArgSString(out_package_name)
	cout_url, _ := unpackArgSString(out_url)
	cout_direct_download, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_direct_download)).Data)), cgoAllocsUnknown
	cout_open_license, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_open_license)).Data)), cgoAllocsUnknown
	cout_available, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_available)).Data)), cgoAllocsUnknown
	__ret := C.proj_grid_get_info_from_database(cctx, cgrid_name, cout_full_name, cout_package_name, cout_url, cout_direct_download, cout_open_license, cout_available)
	packSString(out_url, cout_url)
	packSString(out_package_name, cout_package_name)
	packSString(out_full_name, cout_full_name)
	runtime.KeepAlive(grid_name)
	__v := (int32)(__ret)
	return __v
}

// Clone function as declared in include/proj.h:810
func Clone(ctx []PJ_CONTEXT, obj []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_clone(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Create_from_name function as declared in include/proj.h:812
func Create_from_name(ctx []PJ_CONTEXT, auth_name string, searchedName string, types []PJ_TYPE, typesCount uint, approximateMatch int32, limitResultCount uint, options []string) *PJ_OBJ_LIST {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	auth_name = safeString(auth_name)
	cauth_name, _ := unpackPCharString(auth_name)
	searchedName = safeString(searchedName)
	csearchedName, _ := unpackPCharString(searchedName)
	ctypes, _ := (*C.PJ_TYPE)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&types)).Data)), cgoAllocsUnknown
	ctypesCount, _ := (C.size_t)(typesCount), cgoAllocsUnknown
	capproximateMatch, _ := (C.int)(approximateMatch), cgoAllocsUnknown
	climitResultCount, _ := (C.size_t)(limitResultCount), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_create_from_name(cctx, cauth_name, csearchedName, ctypes, ctypesCount, capproximateMatch, climitResultCount, coptions)
	packSString(options, coptions)
	runtime.KeepAlive(searchedName)
	runtime.KeepAlive(auth_name)
	__v := *(**PJ_OBJ_LIST)(unsafe.Pointer(&__ret))
	return __v
}

// Get_type function as declared in include/proj.h:821
func Get_type(obj []PJ) PJ_TYPE {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_type(cobj)
	__v := (PJ_TYPE)(__ret)
	return __v
}

// Is_deprecated function as declared in include/proj.h:823
func Is_deprecated(obj []PJ) int32 {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_is_deprecated(cobj)
	__v := (int32)(__ret)
	return __v
}

// Get_non_deprecated function as declared in include/proj.h:825
func Get_non_deprecated(ctx []PJ_CONTEXT, obj []PJ) *PJ_OBJ_LIST {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_non_deprecated(cctx, cobj)
	__v := *(**PJ_OBJ_LIST)(unsafe.Pointer(&__ret))
	return __v
}

// Is_equivalent_to function as declared in include/proj.h:828
func Is_equivalent_to(obj []PJ, other []PJ, criterion PJ_COMPARISON_CRITERION) int32 {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	cother, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&other)).Data)), cgoAllocsUnknown
	ccriterion, _ := (C.PJ_COMPARISON_CRITERION)(criterion), cgoAllocsUnknown
	__ret := C.proj_is_equivalent_to(cobj, cother, ccriterion)
	__v := (int32)(__ret)
	return __v
}

// Is_crs function as declared in include/proj.h:831
func Is_crs(obj []PJ) int32 {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_is_crs(cobj)
	__v := (int32)(__ret)
	return __v
}

// Get_name function as declared in include/proj.h:833
func Get_name(obj []PJ) string {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_name(cobj)
	__v := packPCharString(__ret)
	return __v
}

// Get_id_auth_name function as declared in include/proj.h:835
func Get_id_auth_name(obj []PJ, index int32) string {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.proj_get_id_auth_name(cobj, cindex)
	__v := packPCharString(__ret)
	return __v
}

// Get_id_code function as declared in include/proj.h:837
func Get_id_code(obj []PJ, index int32) string {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.proj_get_id_code(cobj, cindex)
	__v := packPCharString(__ret)
	return __v
}

// Get_remarks function as declared in include/proj.h:839
func Get_remarks(obj []PJ) string {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_remarks(cobj)
	__v := packPCharString(__ret)
	return __v
}

// Get_scope function as declared in include/proj.h:841
func Get_scope(obj []PJ) string {
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_scope(cobj)
	__v := packPCharString(__ret)
	return __v
}

// Get_area_of_use function as declared in include/proj.h:843
func Get_area_of_use(ctx []PJ_CONTEXT, obj []PJ, out_west_lon_degree []float64, out_south_lat_degree []float64, out_east_lon_degree []float64, out_north_lat_degree []float64, out_area_name []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	cout_west_lon_degree, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_west_lon_degree)).Data)), cgoAllocsUnknown
	cout_south_lat_degree, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_south_lat_degree)).Data)), cgoAllocsUnknown
	cout_east_lon_degree, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_east_lon_degree)).Data)), cgoAllocsUnknown
	cout_north_lat_degree, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_north_lat_degree)).Data)), cgoAllocsUnknown
	cout_area_name, _ := unpackArgSString(out_area_name)
	__ret := C.proj_get_area_of_use(cctx, cobj, cout_west_lon_degree, cout_south_lat_degree, cout_east_lon_degree, cout_north_lat_degree, cout_area_name)
	packSString(out_area_name, cout_area_name)
	__v := (int32)(__ret)
	return __v
}

// As_wkt function as declared in include/proj.h:851
func As_wkt(ctx []PJ_CONTEXT, obj []PJ, _type PJ_WKT_TYPE, options []string) string {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	c_type, _ := (C.PJ_WKT_TYPE)(_type), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_as_wkt(cctx, cobj, c_type, coptions)
	packSString(options, coptions)
	__v := packPCharString(__ret)
	return __v
}

// As_proj_string function as declared in include/proj.h:855
func As_proj_string(ctx []PJ_CONTEXT, obj []PJ, _type PJ_PROJ_STRING_TYPE, options []string) string {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	c_type, _ := (C.PJ_PROJ_STRING_TYPE)(_type), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_as_proj_string(cctx, cobj, c_type, coptions)
	packSString(options, coptions)
	__v := packPCharString(__ret)
	return __v
}

// As_projjson function as declared in include/proj.h:860
func As_projjson(ctx []PJ_CONTEXT, obj []PJ, options []string) string {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_as_projjson(cctx, cobj, coptions)
	packSString(options, coptions)
	__v := packPCharString(__ret)
	return __v
}

// Get_source_crs function as declared in include/proj.h:864
func Get_source_crs(ctx []PJ_CONTEXT, obj []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_source_crs(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Get_target_crs function as declared in include/proj.h:867
func Get_target_crs(ctx []PJ_CONTEXT, obj []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_target_crs(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Identify function as declared in include/proj.h:870
func Identify(ctx []PJ_CONTEXT, obj []PJ, auth_name string, options []string, out_confidence [][]int32) *PJ_OBJ_LIST {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	auth_name = safeString(auth_name)
	cauth_name, _ := unpackPCharString(auth_name)
	coptions, _ := unpackArgSString(options)
	cout_confidence, _ := unpackArgSSInt32(out_confidence)
	__ret := C.proj_identify(cctx, cobj, cauth_name, coptions, cout_confidence)
	packSSInt32(out_confidence, cout_confidence)
	packSString(options, coptions)
	runtime.KeepAlive(auth_name)
	__v := *(**PJ_OBJ_LIST)(unsafe.Pointer(&__ret))
	return __v
}

// Int_list_destroy function as declared in include/proj.h:876
func Int_list_destroy(list []int32) {
	clist, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&list)).Data)), cgoAllocsUnknown
	C.proj_int_list_destroy(clist)
}

// Get_authorities_from_database function as declared in include/proj.h:880
func Get_authorities_from_database(ctx []PJ_CONTEXT) []*PROJ_STRING_LIST {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_authorities_from_database(cctx)
	__v := (*(*[0x7fffffff]*PROJ_STRING_LIST)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// Get_codes_from_database function as declared in include/proj.h:882
func Get_codes_from_database(ctx []PJ_CONTEXT, auth_name string, _type PJ_TYPE, allow_deprecated int32) []*PROJ_STRING_LIST {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	auth_name = safeString(auth_name)
	cauth_name, _ := unpackPCharString(auth_name)
	c_type, _ := (C.PJ_TYPE)(_type), cgoAllocsUnknown
	callow_deprecated, _ := (C.int)(allow_deprecated), cgoAllocsUnknown
	__ret := C.proj_get_codes_from_database(cctx, cauth_name, c_type, callow_deprecated)
	runtime.KeepAlive(auth_name)
	__v := (*(*[0x7fffffff]*PROJ_STRING_LIST)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// Get_crs_list_parameters_create function as declared in include/proj.h:887
func Get_crs_list_parameters_create() *PROJ_CRS_LIST_PARAMETERS {
	__ret := C.proj_get_crs_list_parameters_create()
	__v := NewPROJ_CRS_LIST_PARAMETERSRef(unsafe.Pointer(__ret))
	return __v
}

// Get_crs_list_parameters_destroy function as declared in include/proj.h:889
func Get_crs_list_parameters_destroy(params []PROJ_CRS_LIST_PARAMETERS) {
	cparams, _ := unpackArgSPROJ_CRS_LIST_PARAMETERS(params)
	C.proj_get_crs_list_parameters_destroy(cparams)
	packSPROJ_CRS_LIST_PARAMETERS(params, cparams)
}

// Get_crs_info_list_from_database function as declared in include/proj.h:892
func Get_crs_info_list_from_database(ctx []PJ_CONTEXT, auth_name string, params []PROJ_CRS_LIST_PARAMETERS, out_result_count []int32) []*PROJ_CRS_INFO {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	auth_name = safeString(auth_name)
	cauth_name, _ := unpackPCharString(auth_name)
	cparams, _ := unpackArgSPROJ_CRS_LIST_PARAMETERS(params)
	cout_result_count, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_result_count)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_crs_info_list_from_database(cctx, cauth_name, cparams, cout_result_count)
	packSPROJ_CRS_LIST_PARAMETERS(params, cparams)
	runtime.KeepAlive(auth_name)
	var __v []*PROJ_CRS_INFO
	packSPPROJ_CRS_INFO(__v, __ret)
	return __v
}

// Crs_info_list_destroy function as declared in include/proj.h:898
func Crs_info_list_destroy(list [][]PROJ_CRS_INFO) {
	clist, _ := unpackArgSSPROJ_CRS_INFO(list)
	C.proj_crs_info_list_destroy(clist)
	packSSPROJ_CRS_INFO(list, clist)
}

// Create_operation_factory_context function as declared in include/proj.h:907
func Create_operation_factory_context(ctx []PJ_CONTEXT, authority string) *PJ_OPERATION_FACTORY_CONTEXT {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	authority = safeString(authority)
	cauthority, _ := unpackPCharString(authority)
	__ret := C.proj_create_operation_factory_context(cctx, cauthority)
	runtime.KeepAlive(authority)
	__v := *(**PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer(&__ret))
	return __v
}

// Operation_factory_context_destroy function as declared in include/proj.h:911
func Operation_factory_context_destroy(ctx []PJ_OPERATION_FACTORY_CONTEXT) {
	cctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	C.proj_operation_factory_context_destroy(cctx)
}

// Operation_factory_context_set_desired_accuracy function as declared in include/proj.h:914
func Operation_factory_context_set_desired_accuracy(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, accuracy float64) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	caccuracy, _ := (C.double)(accuracy), cgoAllocsUnknown
	C.proj_operation_factory_context_set_desired_accuracy(cctx, cfactory_ctx, caccuracy)
}

// Operation_factory_context_set_area_of_interest function as declared in include/proj.h:919
func Operation_factory_context_set_area_of_interest(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, west_lon_degree float64, south_lat_degree float64, east_lon_degree float64, north_lat_degree float64) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	cwest_lon_degree, _ := (C.double)(west_lon_degree), cgoAllocsUnknown
	csouth_lat_degree, _ := (C.double)(south_lat_degree), cgoAllocsUnknown
	ceast_lon_degree, _ := (C.double)(east_lon_degree), cgoAllocsUnknown
	cnorth_lat_degree, _ := (C.double)(north_lat_degree), cgoAllocsUnknown
	C.proj_operation_factory_context_set_area_of_interest(cctx, cfactory_ctx, cwest_lon_degree, csouth_lat_degree, ceast_lon_degree, cnorth_lat_degree)
}

// Operation_factory_context_set_crs_extent_use function as declared in include/proj.h:927
func Operation_factory_context_set_crs_extent_use(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, use PROJ_CRS_EXTENT_USE) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	cuse, _ := (C.PROJ_CRS_EXTENT_USE)(use), cgoAllocsUnknown
	C.proj_operation_factory_context_set_crs_extent_use(cctx, cfactory_ctx, cuse)
}

// Operation_factory_context_set_spatial_criterion function as declared in include/proj.h:932
func Operation_factory_context_set_spatial_criterion(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, criterion PROJ_SPATIAL_CRITERION) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	ccriterion, _ := (C.PROJ_SPATIAL_CRITERION)(criterion), cgoAllocsUnknown
	C.proj_operation_factory_context_set_spatial_criterion(cctx, cfactory_ctx, ccriterion)
}

// Operation_factory_context_set_grid_availability_use function as declared in include/proj.h:938
func Operation_factory_context_set_grid_availability_use(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, use PROJ_GRID_AVAILABILITY_USE) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	cuse, _ := (C.PROJ_GRID_AVAILABILITY_USE)(use), cgoAllocsUnknown
	C.proj_operation_factory_context_set_grid_availability_use(cctx, cfactory_ctx, cuse)
}

// Operation_factory_context_set_use_proj_alternative_grid_names function as declared in include/proj.h:943
func Operation_factory_context_set_use_proj_alternative_grid_names(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, usePROJNames int32) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	cusePROJNames, _ := (C.int)(usePROJNames), cgoAllocsUnknown
	C.proj_operation_factory_context_set_use_proj_alternative_grid_names(cctx, cfactory_ctx, cusePROJNames)
}

// Operation_factory_context_set_allow_use_intermediate_crs function as declared in include/proj.h:948
func Operation_factory_context_set_allow_use_intermediate_crs(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, use PROJ_INTERMEDIATE_CRS_USE) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	cuse, _ := (C.PROJ_INTERMEDIATE_CRS_USE)(use), cgoAllocsUnknown
	C.proj_operation_factory_context_set_allow_use_intermediate_crs(cctx, cfactory_ctx, cuse)
}

// Operation_factory_context_set_allowed_intermediate_crs function as declared in include/proj.h:953
func Operation_factory_context_set_allowed_intermediate_crs(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, list_of_auth_name_codes []string) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	clist_of_auth_name_codes, _ := unpackArgSString(list_of_auth_name_codes)
	C.proj_operation_factory_context_set_allowed_intermediate_crs(cctx, cfactory_ctx, clist_of_auth_name_codes)
	packSString(list_of_auth_name_codes, clist_of_auth_name_codes)
}

// Operation_factory_context_set_discard_superseded function as declared in include/proj.h:958
func Operation_factory_context_set_discard_superseded(ctx []PJ_CONTEXT, factory_ctx []PJ_OPERATION_FACTORY_CONTEXT, discard int32) {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cfactory_ctx, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&factory_ctx)).Data)), cgoAllocsUnknown
	cdiscard, _ := (C.int)(discard), cgoAllocsUnknown
	C.proj_operation_factory_context_set_discard_superseded(cctx, cfactory_ctx, cdiscard)
}

// Create_operations function as declared in include/proj.h:966
func Create_operations(ctx []PJ_CONTEXT, source_crs []PJ, target_crs []PJ, operationContext []PJ_OPERATION_FACTORY_CONTEXT) *PJ_OBJ_LIST {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	csource_crs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&source_crs)).Data)), cgoAllocsUnknown
	ctarget_crs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&target_crs)).Data)), cgoAllocsUnknown
	coperationContext, _ := (*C.PJ_OPERATION_FACTORY_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&operationContext)).Data)), cgoAllocsUnknown
	__ret := C.proj_create_operations(cctx, csource_crs, ctarget_crs, coperationContext)
	__v := *(**PJ_OBJ_LIST)(unsafe.Pointer(&__ret))
	return __v
}

// List_get_count function as declared in include/proj.h:972
func List_get_count(result []PJ_OBJ_LIST) int32 {
	cresult, _ := (*C.PJ_OBJ_LIST)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&result)).Data)), cgoAllocsUnknown
	__ret := C.proj_list_get_count(cresult)
	__v := (int32)(__ret)
	return __v
}

// List_get function as declared in include/proj.h:974
func List_get(ctx []PJ_CONTEXT, result []PJ_OBJ_LIST, index int32) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cresult, _ := (*C.PJ_OBJ_LIST)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&result)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.proj_list_get(cctx, cresult, cindex)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// List_destroy function as declared in include/proj.h:978
func List_destroy(result []PJ_OBJ_LIST) {
	cresult, _ := (*C.PJ_OBJ_LIST)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&result)).Data)), cgoAllocsUnknown
	C.proj_list_destroy(cresult)
}

// Crs_get_geodetic_crs function as declared in include/proj.h:982
func Crs_get_geodetic_crs(ctx []PJ_CONTEXT, crs []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccrs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&crs)).Data)), cgoAllocsUnknown
	__ret := C.proj_crs_get_geodetic_crs(cctx, ccrs)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Crs_get_horizontal_datum function as declared in include/proj.h:984
func Crs_get_horizontal_datum(ctx []PJ_CONTEXT, crs []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccrs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&crs)).Data)), cgoAllocsUnknown
	__ret := C.proj_crs_get_horizontal_datum(cctx, ccrs)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Crs_get_sub_crs function as declared in include/proj.h:986
func Crs_get_sub_crs(ctx []PJ_CONTEXT, crs []PJ, index int32) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccrs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&crs)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.proj_crs_get_sub_crs(cctx, ccrs, cindex)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Crs_get_datum function as declared in include/proj.h:988
func Crs_get_datum(ctx []PJ_CONTEXT, crs []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccrs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&crs)).Data)), cgoAllocsUnknown
	__ret := C.proj_crs_get_datum(cctx, ccrs)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Crs_get_coordinate_system function as declared in include/proj.h:990
func Crs_get_coordinate_system(ctx []PJ_CONTEXT, crs []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccrs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&crs)).Data)), cgoAllocsUnknown
	__ret := C.proj_crs_get_coordinate_system(cctx, ccrs)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Cs_get_type function as declared in include/proj.h:992
func Cs_get_type(ctx []PJ_CONTEXT, cs []PJ) PJ_COORDINATE_SYSTEM_TYPE {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&cs)).Data)), cgoAllocsUnknown
	__ret := C.proj_cs_get_type(cctx, ccs)
	__v := (PJ_COORDINATE_SYSTEM_TYPE)(__ret)
	return __v
}

// Cs_get_axis_count function as declared in include/proj.h:995
func Cs_get_axis_count(ctx []PJ_CONTEXT, cs []PJ) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&cs)).Data)), cgoAllocsUnknown
	__ret := C.proj_cs_get_axis_count(cctx, ccs)
	__v := (int32)(__ret)
	return __v
}

// Cs_get_axis_info function as declared in include/proj.h:998
func Cs_get_axis_info(ctx []PJ_CONTEXT, cs []PJ, index int32, out_name []string, out_abbrev []string, out_direction []string, out_unit_conv_factor []float64, out_unit_name []string, out_unit_auth_name []string, out_unit_code []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&cs)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	cout_name, _ := unpackArgSString(out_name)
	cout_abbrev, _ := unpackArgSString(out_abbrev)
	cout_direction, _ := unpackArgSString(out_direction)
	cout_unit_conv_factor, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_unit_conv_factor)).Data)), cgoAllocsUnknown
	cout_unit_name, _ := unpackArgSString(out_unit_name)
	cout_unit_auth_name, _ := unpackArgSString(out_unit_auth_name)
	cout_unit_code, _ := unpackArgSString(out_unit_code)
	__ret := C.proj_cs_get_axis_info(cctx, ccs, cindex, cout_name, cout_abbrev, cout_direction, cout_unit_conv_factor, cout_unit_name, cout_unit_auth_name, cout_unit_code)
	packSString(out_unit_code, cout_unit_code)
	packSString(out_unit_auth_name, cout_unit_auth_name)
	packSString(out_unit_name, cout_unit_name)
	packSString(out_direction, cout_direction)
	packSString(out_abbrev, cout_abbrev)
	packSString(out_name, cout_name)
	__v := (int32)(__ret)
	return __v
}

// Get_ellipsoid function as declared in include/proj.h:1008
func Get_ellipsoid(ctx []PJ_CONTEXT, obj []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_ellipsoid(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Ellipsoid_get_parameters function as declared in include/proj.h:1011
func Ellipsoid_get_parameters(ctx []PJ_CONTEXT, ellipsoid []PJ, out_semi_major_metre []float64, out_semi_minor_metre []float64, out_is_semi_minor_computed []int32, out_inv_flattening []float64) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cellipsoid, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ellipsoid)).Data)), cgoAllocsUnknown
	cout_semi_major_metre, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_semi_major_metre)).Data)), cgoAllocsUnknown
	cout_semi_minor_metre, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_semi_minor_metre)).Data)), cgoAllocsUnknown
	cout_is_semi_minor_computed, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_is_semi_minor_computed)).Data)), cgoAllocsUnknown
	cout_inv_flattening, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_inv_flattening)).Data)), cgoAllocsUnknown
	__ret := C.proj_ellipsoid_get_parameters(cctx, cellipsoid, cout_semi_major_metre, cout_semi_minor_metre, cout_is_semi_minor_computed, cout_inv_flattening)
	__v := (int32)(__ret)
	return __v
}

// Get_prime_meridian function as declared in include/proj.h:1018
func Get_prime_meridian(ctx []PJ_CONTEXT, obj []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_get_prime_meridian(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Prime_meridian_get_parameters function as declared in include/proj.h:1021
func Prime_meridian_get_parameters(ctx []PJ_CONTEXT, prime_meridian []PJ, out_longitude []float64, out_unit_conv_factor []float64, out_unit_name []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cprime_meridian, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&prime_meridian)).Data)), cgoAllocsUnknown
	cout_longitude, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_longitude)).Data)), cgoAllocsUnknown
	cout_unit_conv_factor, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_unit_conv_factor)).Data)), cgoAllocsUnknown
	cout_unit_name, _ := unpackArgSString(out_unit_name)
	__ret := C.proj_prime_meridian_get_parameters(cctx, cprime_meridian, cout_longitude, cout_unit_conv_factor, cout_unit_name)
	packSString(out_unit_name, cout_unit_name)
	__v := (int32)(__ret)
	return __v
}

// Crs_get_coordoperation function as declared in include/proj.h:1027
func Crs_get_coordoperation(ctx []PJ_CONTEXT, crs []PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccrs, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&crs)).Data)), cgoAllocsUnknown
	__ret := C.proj_crs_get_coordoperation(cctx, ccrs)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Coordoperation_get_method_info function as declared in include/proj.h:1030
func Coordoperation_get_method_info(ctx []PJ_CONTEXT, coordoperation []PJ, out_method_name []string, out_method_auth_name []string, out_method_code []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	cout_method_name, _ := unpackArgSString(out_method_name)
	cout_method_auth_name, _ := unpackArgSString(out_method_auth_name)
	cout_method_code, _ := unpackArgSString(out_method_code)
	__ret := C.proj_coordoperation_get_method_info(cctx, ccoordoperation, cout_method_name, cout_method_auth_name, cout_method_code)
	packSString(out_method_code, cout_method_code)
	packSString(out_method_auth_name, cout_method_auth_name)
	packSString(out_method_name, cout_method_name)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_is_instantiable function as declared in include/proj.h:1036
func Coordoperation_is_instantiable(ctx []PJ_CONTEXT, coordoperation []PJ) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	__ret := C.proj_coordoperation_is_instantiable(cctx, ccoordoperation)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_has_ballpark_transformation function as declared in include/proj.h:1039
func Coordoperation_has_ballpark_transformation(ctx []PJ_CONTEXT, coordoperation []PJ) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	__ret := C.proj_coordoperation_has_ballpark_transformation(cctx, ccoordoperation)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_get_param_count function as declared in include/proj.h:1042
func Coordoperation_get_param_count(ctx []PJ_CONTEXT, coordoperation []PJ) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	__ret := C.proj_coordoperation_get_param_count(cctx, ccoordoperation)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_get_param_index function as declared in include/proj.h:1045
func Coordoperation_get_param_index(ctx []PJ_CONTEXT, coordoperation []PJ, name string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	name = safeString(name)
	cname, _ := unpackPCharString(name)
	__ret := C.proj_coordoperation_get_param_index(cctx, ccoordoperation, cname)
	runtime.KeepAlive(name)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_get_param function as declared in include/proj.h:1049
func Coordoperation_get_param(ctx []PJ_CONTEXT, coordoperation []PJ, index int32, out_name []string, out_auth_name []string, out_code []string, out_value []float64, out_value_string []string, out_unit_conv_factor []float64, out_unit_name []string, out_unit_auth_name []string, out_unit_code []string, out_unit_category []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	cout_name, _ := unpackArgSString(out_name)
	cout_auth_name, _ := unpackArgSString(out_auth_name)
	cout_code, _ := unpackArgSString(out_code)
	cout_value, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_value)).Data)), cgoAllocsUnknown
	cout_value_string, _ := unpackArgSString(out_value_string)
	cout_unit_conv_factor, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_unit_conv_factor)).Data)), cgoAllocsUnknown
	cout_unit_name, _ := unpackArgSString(out_unit_name)
	cout_unit_auth_name, _ := unpackArgSString(out_unit_auth_name)
	cout_unit_code, _ := unpackArgSString(out_unit_code)
	cout_unit_category, _ := unpackArgSString(out_unit_category)
	__ret := C.proj_coordoperation_get_param(cctx, ccoordoperation, cindex, cout_name, cout_auth_name, cout_code, cout_value, cout_value_string, cout_unit_conv_factor, cout_unit_name, cout_unit_auth_name, cout_unit_code, cout_unit_category)
	packSString(out_unit_category, cout_unit_category)
	packSString(out_unit_code, cout_unit_code)
	packSString(out_unit_auth_name, cout_unit_auth_name)
	packSString(out_unit_name, cout_unit_name)
	packSString(out_value_string, cout_value_string)
	packSString(out_code, cout_code)
	packSString(out_auth_name, cout_auth_name)
	packSString(out_name, cout_name)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_get_grid_used_count function as declared in include/proj.h:1063
func Coordoperation_get_grid_used_count(ctx []PJ_CONTEXT, coordoperation []PJ) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	__ret := C.proj_coordoperation_get_grid_used_count(cctx, ccoordoperation)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_get_grid_used function as declared in include/proj.h:1066
func Coordoperation_get_grid_used(ctx []PJ_CONTEXT, coordoperation []PJ, index int32, out_short_name []string, out_full_name []string, out_package_name []string, out_url []string, out_direct_download []int32, out_open_license []int32, out_available []int32) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	cout_short_name, _ := unpackArgSString(out_short_name)
	cout_full_name, _ := unpackArgSString(out_full_name)
	cout_package_name, _ := unpackArgSString(out_package_name)
	cout_url, _ := unpackArgSString(out_url)
	cout_direct_download, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_direct_download)).Data)), cgoAllocsUnknown
	cout_open_license, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_open_license)).Data)), cgoAllocsUnknown
	cout_available, _ := (*C.int)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_available)).Data)), cgoAllocsUnknown
	__ret := C.proj_coordoperation_get_grid_used(cctx, ccoordoperation, cindex, cout_short_name, cout_full_name, cout_package_name, cout_url, cout_direct_download, cout_open_license, cout_available)
	packSString(out_url, cout_url)
	packSString(out_package_name, cout_package_name)
	packSString(out_full_name, cout_full_name)
	packSString(out_short_name, cout_short_name)
	__v := (int32)(__ret)
	return __v
}

// Coordoperation_get_accuracy function as declared in include/proj.h:1077
func Coordoperation_get_accuracy(ctx []PJ_CONTEXT, obj []PJ) float64 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&obj)).Data)), cgoAllocsUnknown
	__ret := C.proj_coordoperation_get_accuracy(cctx, cobj)
	__v := (float64)(__ret)
	return __v
}

// Coordoperation_get_towgs84_values function as declared in include/proj.h:1080
func Coordoperation_get_towgs84_values(ctx []PJ_CONTEXT, coordoperation []PJ, out_values []float64, value_count int32, emit_error_if_incompatible int32) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	ccoordoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&coordoperation)).Data)), cgoAllocsUnknown
	cout_values, _ := (*C.double)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&out_values)).Data)), cgoAllocsUnknown
	cvalue_count, _ := (C.int)(value_count), cgoAllocsUnknown
	cemit_error_if_incompatible, _ := (C.int)(emit_error_if_incompatible), cgoAllocsUnknown
	__ret := C.proj_coordoperation_get_towgs84_values(cctx, ccoordoperation, cout_values, cvalue_count, cemit_error_if_incompatible)
	__v := (int32)(__ret)
	return __v
}

// Concatoperation_get_step_count function as declared in include/proj.h:1086
func Concatoperation_get_step_count(ctx []PJ_CONTEXT, concatoperation []PJ) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cconcatoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&concatoperation)).Data)), cgoAllocsUnknown
	__ret := C.proj_concatoperation_get_step_count(cctx, cconcatoperation)
	__v := (int32)(__ret)
	return __v
}

// Concatoperation_get_step function as declared in include/proj.h:1089
func Concatoperation_get_step(ctx []PJ_CONTEXT, concatoperation []PJ, i_step int32) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&ctx)).Data)), cgoAllocsUnknown
	cconcatoperation, _ := (*C.PJ)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&concatoperation)).Data)), cgoAllocsUnknown
	ci_step, _ := (C.int)(i_step), cgoAllocsUnknown
	__ret := C.proj_concatoperation_get_step(cctx, cconcatoperation, ci_step)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}
