// WARNING: This file has automatically been generated on Wed, 01 Jan 2020 21:23:02 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// Context_create function as declared in include/proj.h:344
func Context_create() *PJ_CONTEXT {
	__ret := C.proj_context_create()
	__v := *(**PJ_CONTEXT)(unsafe.Pointer(&__ret))
	return __v
}

// Context_destroy function as declared in include/proj.h:345
func Context_destroy(ctx *PJ_CONTEXT) *PJ_CONTEXT {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.proj_context_destroy(cctx)
	__v := *(**PJ_CONTEXT)(unsafe.Pointer(&__ret))
	return __v
}

// Create function as declared in include/proj.h:357
func Create(ctx *PJ_CONTEXT, definition string) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	definition = safeString(definition)
	cdefinition, _ := unpackPCharString(definition)
	__ret := C.proj_create(cctx, cdefinition)
	runtime.KeepAlive(definition)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Create_crs_to_crs_from_pj function as declared in include/proj.h:360
func Create_crs_to_crs_from_pj(ctx *PJ_CONTEXT, source_crs *PJ, target_crs *PJ, area *PJ_AREA, options []string) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	csource_crs, _ := (*C.PJ)(unsafe.Pointer(source_crs)), cgoAllocsUnknown
	ctarget_crs, _ := (*C.PJ)(unsafe.Pointer(target_crs)), cgoAllocsUnknown
	carea, _ := (*C.PJ_AREA)(unsafe.Pointer(area)), cgoAllocsUnknown
	coptions, _ := unpackArgSString(options)
	__ret := C.proj_create_crs_to_crs_from_pj(cctx, csource_crs, ctarget_crs, carea, coptions)
	packSString(options, coptions)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Normalize_for_visualization function as declared in include/proj.h:365
func Normalize_for_visualization(ctx *PJ_CONTEXT, obj *PJ) *PJ {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer(obj)), cgoAllocsUnknown
	__ret := C.proj_normalize_for_visualization(cctx, cobj)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Destroy function as declared in include/proj.h:366
func Destroy(P *PJ) *PJ {
	cP, _ := (*C.PJ)(unsafe.Pointer(P)), cgoAllocsUnknown
	__ret := C.proj_destroy(cP)
	__v := *(**PJ)(unsafe.Pointer(&__ret))
	return __v
}

// Trans function as declared in include/proj.h:390
func Trans(P *PJ, direction PJ_DIRECTION, coord PJ_COORD) PJ_COORD {
	cP, _ := (*C.PJ)(unsafe.Pointer(P)), cgoAllocsUnknown
	cdirection, _ := (C.PJ_DIRECTION)(direction), cgoAllocsUnknown
	ccoord, _ := *(*C.PJ_COORD)(unsafe.Pointer(&coord)), cgoAllocsUnknown
	__ret := C.proj_trans(cP, cdirection, ccoord)
	__v := *(*PJ_COORD)(unsafe.Pointer(&__ret))
	return __v
}

// Get_area_of_use function as declared in include/proj.h:843
func Get_area_of_use(ctx *PJ_CONTEXT, obj *PJ, out_west_lon_degree *float64, out_south_lat_degree *float64, out_east_lon_degree *float64, out_north_lat_degree *float64, out_area_name []string) int32 {
	cctx, _ := (*C.PJ_CONTEXT)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cobj, _ := (*C.PJ)(unsafe.Pointer(obj)), cgoAllocsUnknown
	cout_west_lon_degree, _ := (*C.double)(unsafe.Pointer(out_west_lon_degree)), cgoAllocsUnknown
	cout_south_lat_degree, _ := (*C.double)(unsafe.Pointer(out_south_lat_degree)), cgoAllocsUnknown
	cout_east_lon_degree, _ := (*C.double)(unsafe.Pointer(out_east_lon_degree)), cgoAllocsUnknown
	cout_north_lat_degree, _ := (*C.double)(unsafe.Pointer(out_north_lat_degree)), cgoAllocsUnknown
	cout_area_name, _ := unpackArgSString(out_area_name)
	__ret := C.proj_get_area_of_use(cctx, cobj, cout_west_lon_degree, cout_south_lat_degree, cout_east_lon_degree, cout_north_lat_degree, cout_area_name)
	packSString(out_area_name, cout_area_name)
	__v := (int32)(__ret)
	return __v
}
