// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 17 Dec 2019 13:19:11 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package cproj provides Go bindings for PROJ - a library for performing conversions
between cartographic projections, maintained by the OSGeo organization.
See https://proj.org for information.
These bindings are generated by "c-for-go" (see https://c.for-go.com).
*/
package cproj
