// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Dec 2019 15:08:31 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// PJ_COORD as declared in include/proj.h:165
const sizeofPJ_COORD = unsafe.Sizeof(C.PJ_COORD{})

type PJ_COORD [sizeofPJ_COORD]byte

// PJ_AREA as declared in include/proj.h:168
type PJ_AREA C.PJ_AREA

// PJ_FACTORS as declared in include/proj.h:185
type PJ_FACTORS struct {
	meridional_scale        float64
	parallel_scale          float64
	areal_scale             float64
	angular_distortion      float64
	meridian_parallel_angle float64
	meridian_convergence    float64
	tissot_semimajor        float64
	tissot_semiminor        float64
	dx_dlam                 float64
	dx_dphi                 float64
	dy_dlam                 float64
	dy_dphi                 float64
	ref24ee504e             *C.PJ_FACTORS
	allocs24ee504e          interface{}
}

// PJ as declared in include/proj.h:189
type PJ C.PJ

// PJ_INFO as declared in include/proj.h:193
type PJ_INFO C.PJ_INFO

// PJ_PROJ_INFO as declared in include/proj.h:196
type PJ_PROJ_INFO struct {
	id             string
	description    string
	definition     string
	has_inverse    int32
	accuracy       float64
	ref249cc27f    *C.PJ_PROJ_INFO
	allocs249cc27f interface{}
}

// PJ_GRID_INFO as declared in include/proj.h:199
type PJ_GRID_INFO struct {
	gridname       [32]byte
	filename       [260]byte
	format         [8]byte
	n_lon          int32
	n_lat          int32
	cs_lon         float64
	cs_lat         float64
	refb5e7b98d    *C.PJ_GRID_INFO
	allocsb5e7b98d interface{}
}

// PJ_INIT_INFO as declared in include/proj.h:202
type PJ_INIT_INFO struct {
	name           [32]byte
	filename       [260]byte
	version        [32]byte
	origin         [32]byte
	lastupdate     [16]byte
	ref55e744e0    *C.PJ_INIT_INFO
	allocs55e744e0 interface{}
}

// PJ_OPERATIONS as declared in include/proj.h:211
type PJ_OPERATIONS C.PJ_OPERATIONS

// PJ_ELLPS as declared in include/proj.h:219
type PJ_ELLPS struct {
	id             string
	major          string
	ell            string
	name           string
	ref5d2fa5b8    *C.PJ_ELLPS
	allocs5d2fa5b8 interface{}
}

// PJ_UNITS as declared in include/proj.h:227
type PJ_UNITS struct {
	id             string
	to_meter       string
	name           string
	factor         float64
	reff561fd5e    *C.PJ_UNITS
	allocsf561fd5e interface{}
}

// PJ_PRIME_MERIDIANS as declared in include/proj.h:233
type PJ_PRIME_MERIDIANS struct {
	id             string
	defn           string
	ref9dd6bf1e    *C.PJ_PRIME_MERIDIANS
	allocs9dd6bf1e interface{}
}

// PJ_CONTEXT as declared in include/proj.h:327
type PJ_CONTEXT C.PJ_CONTEXT

// PROJ_STRING_LIST type as declared in include/proj.h:476
type PROJ_STRING_LIST [][]byte

// PROJ_CRS_INFO as declared in include/proj.h:703
type PROJ_CRS_INFO struct {
	auth_name              []byte
	code                   []byte
	name                   []byte
	_type                  PJ_TYPE
	deprecated             int32
	bbox_valid             int32
	west_lon_degree        float64
	south_lat_degree       float64
	east_lon_degree        float64
	north_lat_degree       float64
	area_name              []byte
	projection_method_name []byte
	ref48245dab            *C.PROJ_CRS_INFO
	allocs48245dab         interface{}
}

// PROJ_CRS_LIST_PARAMETERS as declared in include/proj.h:737
type PROJ_CRS_LIST_PARAMETERS struct {
	types                         []PJ_TYPE
	typesCount                    uint
	crs_area_of_use_contains_bbox int32
	bbox_valid                    int32
	west_lon_degree               float64
	south_lat_degree              float64
	east_lon_degree               float64
	north_lat_degree              float64
	allow_deprecated              int32
	ref577cd7ca                   *C.PROJ_CRS_LIST_PARAMETERS
	allocs577cd7ca                interface{}
}

// PJ_OBJ_LIST as declared in include/proj.h:760
type PJ_OBJ_LIST C.PJ_OBJ_LIST

// PJ_OPERATION_FACTORY_CONTEXT as declared in include/proj.h:904
type PJ_OPERATION_FACTORY_CONTEXT C.PJ_OPERATION_FACTORY_CONTEXT
