// WARNING: This file has automatically been generated on Sat, 11 Dec 2021 12:35:48 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// PJ_COORD as declared in include/proj.h:197
const sizeofPJ_COORD = unsafe.Sizeof(C.PJ_COORD{})

type PJ_COORD [sizeofPJ_COORD]byte

// PJ_AREA as declared in include/proj.h:200
type PJ_AREA C.PJ_AREA

// PJ as declared in include/proj.h:221
type PJ C.PJ

// PJ_CONTEXT as declared in include/proj.h:359
type PJ_CONTEXT C.PJ_CONTEXT
