// WARNING: This file has automatically been generated on Sun, 02 May 2021 14:00:37 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cproj

/*
#cgo LDFLAGS: -lproj
#include "proj.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// PJ_COORD as declared in include/proj.h:165
const sizeofPJ_COORD = unsafe.Sizeof(C.PJ_COORD{})

type PJ_COORD [sizeofPJ_COORD]byte

// PJ_AREA as declared in include/proj.h:168
type PJ_AREA C.PJ_AREA

// PJ as declared in include/proj.h:189
type PJ C.PJ

// PJ_CONTEXT as declared in include/proj.h:327
type PJ_CONTEXT C.PJ_CONTEXT

// PROJ_STRING_LIST type as declared in include/proj.h:476
type PROJ_STRING_LIST [][]byte

// PROJ_CRS_INFO as declared in include/proj.h:703
type PROJ_CRS_INFO struct {
	auth_name              []byte
	code                   []byte
	name                   []byte
	deprecated             int32
	bbox_valid             int32
	west_lon_degree        float64
	south_lat_degree       float64
	east_lon_degree        float64
	north_lat_degree       float64
	area_name              []byte
	projection_method_name []byte
	ref48245dab            *C.PROJ_CRS_INFO
	allocs48245dab         interface{}
}

// PROJ_CRS_LIST_PARAMETERS as declared in include/proj.h:737
type PROJ_CRS_LIST_PARAMETERS struct {
	typesCount                    uint32
	crs_area_of_use_contains_bbox int32
	bbox_valid                    int32
	west_lon_degree               float64
	south_lat_degree              float64
	east_lon_degree               float64
	north_lat_degree              float64
	allow_deprecated              int32
	ref577cd7ca                   *C.PROJ_CRS_LIST_PARAMETERS
	allocs577cd7ca                interface{}
}
